run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 65
  cyclop:
    max-complexity: 30
  funlen:
    lines: 200
    statements: 120
  mnd:
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "14"
      - "16"
      - "18"
      - "32"
      - "36"
      - "40"
      - "42"
      - "45"
      - "48"
      - "72"
      - "80"
      - "100"
      - "128"
      - "255"
      - "500"
      - "700"
      - "1000"
      - "1024"
      - "2000"
      - "5000"
      - "0xD8"
      - "0xFF"
      - "0xDA"
      - "0x40"
      - "0x80"
      - "0.55"
      - "0.85"
      - "0.5"
      - "13"
      - "15"
      - "17"
      - "50"
      - "52"
      - "54"
      - "70"
      - "34"
      - "85"
      - "86"
      - "262"
      - "65536"
      - "0x02"
      - "0x04"
      - "0x00010000"
      - "0xB1B0AFBA"
      - "0xFFFF"
      - "1000.0"
      - "3400.0"
  gosec:
    excludes:
      - G115
      - G404
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - cyclop
        - funlen
    - path: sampledata/
      linters:
        - gocyclo
        - gocognit
        - cyclop
        - funlen

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - decorder
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - interfacebloat
    - makezero
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck